######################################################################
# Automatically generated by qmake (3.0) Sat Feb 6 01:44:48 2016
######################################################################

TEMPLATE = app
TARGET = birthdays
INCLUDEPATH += .

# Input
HEADERS += birthdays.h
SOURCES += main.cpp
