######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 19 20:49:33 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += computer.h simulatorgui.h
FORMS += simulatorgui.ui
SOURCES += computer.cpp main.cpp simulatorgui.cpp
