######################################################################
# Automatically generated by qmake (3.0) Sat Feb 20 19:52:37 2016
######################################################################

TEMPLATE = app
TARGET = R1
INCLUDEPATH += .

# Input
HEADERS += film.h
SOURCES += film.cpp main.cpp
