######################################################################
# Automatically generated by qmake (3.0) Wed Feb 3 22:08:24 2016
######################################################################

TEMPLATE = app
TARGET = example6_18to6_19
INCLUDEPATH += .

# Input
HEADERS += account.h
SOURCES += account-client.cpp account.cpp
