######################################################################
# Automatically generated by qmake (3.0) Thu Jan 14 22:56:46 2016
######################################################################

TEMPLATE = app
TARGET = example1_17
INCLUDEPATH += .

# Input
SOURCES += qliterals.cpp
