######################################################################
# Automatically generated by qmake (3.0) Sat Mar 12 12:42:09 2016
######################################################################

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
TEMPLATE = app
TARGET = extracted
INCLUDEPATH += .



# Input
HEADERS += Dictionary.h mainwindow.h ui_mainwindow.h
FORMS += mainwindow.ui
SOURCES += Dictionary.cpp main.cpp mainwindow.cpp
