######################################################################
# Automatically generated by qmake (3.0) Tue Jan 26 14:03:15 2016
######################################################################

TEMPLATE = app
TARGET = hello_world_qt
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
