######################################################################
# Automatically generated by qmake (3.0) Tue Dec 6 13:57:02 2016
######################################################################

TEMPLATE = app
TARGET = Project4
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
