######################################################################
# Automatically generated by qmake (3.0) Tue Jan 27 01:12:35 2015
######################################################################

TEMPLATE = app
TARGET = HW1-example
INCLUDEPATH += .

# Input
HEADERS += calendar.h qstd.h utils_export.h
SOURCES += calendar.cpp main.cpp qstd.cpp
