######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 4 10:54:24 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += qt debug

# Input
SOURCES += main.cpp
