######################################################################
# Automatically generated by qmake (3.0) Tue Feb 2 22:44:59 2016
######################################################################

TEMPLATE = app
TARGET = example6_6to6_7
INCLUDEPATH += .

# Input
HEADERS += student.h
SOURCES += student-test.cpp student.cpp
