######################################################################
# Automatically generated by qmake (3.0) Wed Jan 27 09:24:40 2016
######################################################################

TEMPLATE = app
TARGET = example4_3
INCLUDEPATH += .

# Input
SOURCES += diriterator.cpp
