######################################################################
# Automatically generated by qmake (3.0) Wed Jan 27 09:17:14 2016
######################################################################

TEMPLATE = app
TARGET = example4_2
INCLUDEPATH += .

# Input
SOURCES += recurseadddir.cpp
