######################################################################
# Automatically generated by qmake (3.0) Thu Feb 5 09:23:47 2015
######################################################################

TEMPLATE = app
TARGET = qapp-new
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += main.cpp
