######################################################################
# Automatically generated by qmake (3.0) Thu Feb 26 09:29:23 2015
######################################################################

TEMPLATE = app
TARGET = simpleSlot
INCLUDEPATH += .

# Input
HEADERS += simpleSlot.h
SOURCES += main.cpp simpleSlot.cpp
