######################################################################
# Automatically generated by qmake (3.0) Mon Jan 25 18:46:51 2016
######################################################################

TEMPLATE = app
TARGET = example3_1to3_3
INCLUDEPATH += .

# Input
SOURCES += qtio-demo.cpp
