######################################################################
# Automatically generated by qmake (3.0) Sat Jan 31 22:29:58 2015
######################################################################

TEMPLATE = app
TARGET = myBillings
INCLUDEPATH += .

# Input
HEADERS += argumentlist.h myBillings.h qstd.h utils_export.h
SOURCES += argumentlist.cpp main.cpp myBillings.cpp qstd.cpp
