######################################################################
# Automatically generated by qmake (3.0) Sun Jan 24 21:25:28 2016
######################################################################

TEMPLATE = app
TARGET = example1_10
INCLUDEPATH += .

# Input
SOURCES += qtstreamdemo.cpp
