######################################################################
# Automatically generated by qmake (3.0) Thu Feb 5 09:21:33 2015
######################################################################

TEMPLATE = app
TARGET = qapp
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += main.cpp
