######################################################################
# Automatically generated by qmake (3.0) Sat Mar 12 13:56:01 2016
######################################################################

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = Extractedhw4
INCLUDEPATH += .

# Input
HEADERS += mainWindow.h
SOURCES += hw4Main.cpp mainWindow.cpp
