######################################################################
# Automatically generated by qmake (3.0) Sun Feb 21 22:28:00 2016
######################################################################

QT += core gui widgets
TEMPLATE = app
TARGET = example10_2
INCLUDEPATH += .

# Input
SOURCES += dialogs.cpp

HEADERS += dialogs.h

