######################################################################
# Automatically generated by qmake (3.0) Thu Feb 12 10:00:11 2015
######################################################################

TEMPLATE = app
TARGET = qhash2
INCLUDEPATH += .
DEFINES += QT_NO_DEBUG_OUTPUT

# Input
SOURCES += main.cpp
