######################################################################
# Automatically generated by qmake (3.0) Sun Feb 14 23:24:02 2016
######################################################################

TEMPLATE = app
TARGET = example8_5to8_9
INCLUDEPATH += .
CONFIG += qtestlib

# Input
HEADERS += testassertequals.h
SOURCES += testassertequals.cpp
