######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 4 10:53:38 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += clargs.cpp
