######################################################################
# Automatically generated by qmake (3.0) Thu Feb 12 09:58:59 2015
######################################################################

TEMPLATE = app
TARGET = qhash
INCLUDEPATH += .

# Input
SOURCES += main.cpp
