######################################################################
# Automatically generated by qmake (3.0) Tue Feb 2 23:37:37 2016
######################################################################

TEMPLATE = app
TARGET = example6_13to6_16
INCLUDEPATH += .

# Input
HEADERS += shapes.h
SOURCES += shapes-test.cpp shapes.cpp
