######################################################################
# Automatically generated by qmake (3.0) Wed Mar 4 16:15:28 2015
######################################################################

TEMPLATE = app
TARGET = unitTest
INCLUDEPATH += .

# Input
SOURCES += testProcessLine.cpp
