######################################################################
# Automatically generated by qmake (3.0) Mon Jan 25 22:05:18 2016
######################################################################

TEMPLATE = app
TARGET = example4_1
INCLUDEPATH += .

# Input
SOURCES += lists-examples.cpp
