######################################################################
# Automatically generated by qmake (2.01a) Mon Feb 4 14:55:01 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Billing.h
SOURCES += Billing.cpp main.cpp

OTHER_FILES += \
    mybillings.dat
