######################################################################
# Automatically generated by qmake (3.0) Sat Mar 12 16:14:15 2016
######################################################################

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = example10_3to10_6
INCLUDEPATH += .

# Input
HEADERS += eMainwindow.h study.h
SOURCES += eMain.cpp eMainwindow.cpp study.cpp
