######################################################################
# Automatically generated by qmake (3.0) Sun Jan 24 19:37:59 2016
######################################################################

TEMPLATE = app
TARGET = example1_8
INCLUDEPATH += .

# Input
SOURCES += qstringdemo.cpp
