######################################################################
# Automatically generated by qmake (3.0) Sun Jan 24 22:30:47 2016
######################################################################

TEMPLATE = app
TARGET = example1_14
INCLUDEPATH += .

# Input
SOURCES += qdemo.cpp
