######################################################################
# Automatically generated by qmake (3.0) Sun Feb 22 12:46:51 2015
######################################################################

TEMPLATE = app
TARGET = processFile
INCLUDEPATH += .
QT += widgets
DEFINES += QT_NO_DEBUG_OUTPUT

# Input
HEADERS += qstd.h utils_export.h
SOURCES += main.cpp qstd.cpp processLine.cpp
