######################################################################
# Automatically generated by qmake (3.0) Wed Jan 27 12:32:14 2016
######################################################################

TEMPLATE = app
TARGET = example5_3to5_5
INCLUDEPATH += .

# Input
HEADERS += date.h
SOURCES += date-test.cpp date.cpp
