######################################################################
# Automatically generated by qmake (3.0) Sat Mar 12 14:01:19 2016
######################################################################

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = example10_2
INCLUDEPATH += .

# Input
HEADERS += dialogs.h
SOURCES += dialogs.cpp
