######################################################################
# Automatically generated by qmake (3.0) Thu Feb 26 14:39:12 2015
######################################################################

TEMPLATE = app
TARGET = simpleSlot
INCLUDEPATH += .

# Input
HEADERS += simpleSlot.h
SOURCES += main.cpp simpleSlot.cpp
