######################################################################
# Automatically generated by qmake (3.0) Sun Feb 21 16:16:48 2016
######################################################################

TEMPLATE = app
TARGET = R2
INCLUDEPATH += .

# Input
HEADERS += library.h libraryui.h
SOURCES += library.cpp libraryClient-v2.cpp libraryui.cpp
