######################################################################
# Automatically generated by qmake (3.0) Thu Feb 26 14:38:42 2015
######################################################################

TEMPLATE = app
TARGET = person
INCLUDEPATH += .

# Input
HEADERS += person.h
SOURCES += bunch.cpp person.cpp
