cd: cd.cpp
	$(CXX) -o $@ $^
cd_virtual: cd_virtual.cpp
	$(CXX) -o $@ $^
cdptr: cdptr.cpp
	$(CXX) -o $@ $^
cdptr_warn: cdptr_warn.cpp
	$(CXX) -o $@ $^
cdptr_virtual: cdptr_virtual.cpp
	$(CXX) -o $@ $^
all: cd cd_virtual cdptr cdptr_warn cdptr_virtual
	
clean:
	$(RM) cd cd_virtual cdptr cdptr_warn cdptr_virtual


