######################################################################
# Automatically generated by qmake (3.0) Thu Feb 19 09:52:29 2015
######################################################################

TEMPLATE = app
TARGET = simplemainwindow
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += simplemainwindow.h
SOURCES += main.cpp simplemainwindow.cpp
