######################################################################
# Automatically generated by qmake (3.0) Sat Mar 12 16:37:23 2016
######################################################################
QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
TEMPLATE = app
TARGET = connect
INCLUDEPATH += .

# Input
HEADERS += widget.h
FORMS += widget.ui
SOURCES += main.cpp widget.cpp
