######################################################################
# Automatically generated by qmake (3.0) Tue Feb 2 12:47:59 2016
######################################################################

TEMPLATE = app
TARGET = example6_1to6_5
INCLUDEPATH += .

# Input
HEADERS += student.h
SOURCES += student-test.cpp student.cpp
