######################################################################
# Automatically generated by qmake (3.0) Sat Mar 12 12:40:25 2016
######################################################################

TEMPLATE = app
TARGET = HW3_YU_THOMAS
INCLUDEPATH += .

# Input
HEADERS += dictionary.h mainwindow.h ui_mainwindow.h
FORMS += mainwindow.ui
SOURCES += dictionary.cpp main.cpp mainwindow.cpp
