######################################################################
# Automatically generated by qmake (3.0) Fri Apr 8 15:35:12 2016
######################################################################


QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = RefVid
INCLUDEPATH += .

LIBS += -lrt

# Input
SOURCES += mainVid.cpp
